name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            build_type: 'linux'
          - os: macos-13
            build_type: 'macos'
          - os: windows-2022
            build_type: 'windows'
          - os: ubuntu-22.04-arm
            build_type: 'linux-arm64'
          - os: ubuntu-22.04
            build_type: 'alpine-musl'
          - os: ubuntu-22.04-arm
            build_type: 'alpine-musl-arm64'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Libraries (Linux only)
      if: runner.os == 'Linux' && matrix.build_type != 'alpine-musl' && matrix.build_type != 'alpine-musl-arm64'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev \
        libxcb-shape0-dev \
        libxcb-image0-dev \
        libxkbcommon-x11-0 \
        libxcb-icccm4-dev \
        libxcb-xkb-dev \
        libxcb-render-util0-dev \
        libxcb-keysyms1-dev \
        libxcb-cursor-dev

    - name: Set up Python
      if: matrix.build_type != 'alpine-musl' && matrix.build_type != 'alpine-musl-arm64'
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: matrix.build_type != 'alpine-musl' && matrix.build_type != 'alpine-musl-arm64'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
        pip install -r src/requirements.txt

    - name: Install comtypes (Windows only)
      if: runner.os == 'Windows'
      run: pip install comtypes

    - name: Build in Alpine Docker Container
      if: matrix.build_type == 'alpine-musl' || matrix.build_type == 'alpine-musl-arm64'
      run: |
        if [[ "${{ matrix.build_type }}" == "alpine-musl-arm64" ]]; then
          PLATFORM="--platform linux/arm64"
        else
          PLATFORM="--platform linux/amd64"
        fi
        
        docker run $PLATFORM -v ${{ github.workspace }}:/workspace -w /workspace alpine:latest sh -c "
          # Install build dependencies including PySide6 from Alpine packages
          apk add --no-cache python3 python3-dev py3-pip build-base git \
          linux-headers musl-dev gcc g++ cmake ninja pkgconfig \
          alsa-lib-dev patchelf \
          py3-pyside6 py3-shiboken6 py3-wheel py3-setuptools && \\
          
          # Create virtual environment with system site packages to access PySide6
          python3 -m venv --system-site-packages /opt/venv && \\
          source /opt/venv/bin/activate && \\
          
          # Upgrade pip and install build tools
          pip install --upgrade pip && \\
          
          # Install Nuitka
          pip install -U 'https://github.com/Nuitka/Nuitka/archive/develop.zip' && \\
          
          # Install other requirements via pip
          pip install mido requests zeroconf python-rtmidi && \\
          
          # Verify PySide6 and shiboken6 are available
          python -c 'import PySide6; print(\"PySide6 version:\", PySide6.__version__)' && \\
          python -c 'import shiboken6; print(\"shiboken6 available\")' && \\
          
          # Find shiboken6 library path for inclusion
          SHIBOKEN_PATH=\$(python -c 'import shiboken6; import os; print(os.path.dirname(shiboken6.__file__))') && \\
          echo \"Shiboken6 path: \$SHIBOKEN_PATH\" && \\
          
          # Create output directory
          mkdir -p dist_nuitka && \\
          
          # Build with Nuitka using PySide6 plugin - include shiboken6 and PySide6 sub-modules explicitly
          python -m nuitka --enable-plugin=pyside6 --include-package=zeroconf --include-package=rtmidi --include-package=mido.backends.rtmidi --include-package=shiboken6 --include-package=PySide6.QtCore --include-package=PySide6.QtWidgets --include-package=PySide6.QtGui --include-package=PySide6.QtSvgWidgets --include-data-dir=src/midi_commands=midi_commands --include-data-dir=src/data=data --include-data-dir=src/images=images --prefer-source-code --assume-yes-for-downloads --output-dir=dist_nuitka --onefile --lto=yes 'src/MiniDexed Service Utility.py' && \\
          
          # Clean up build artifacts
          rm -rf dist_nuitka/*build && \\
          rm -rf dist_nuitka/*dist
        "

    - name: Build Executable (Nuitka)
      if: matrix.build_type != 'alpine-musl' && matrix.build_type != 'alpine-musl-arm64'
      run: |
          python -m nuitka --version
          python -m pip list -v
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            python -m nuitka --assume-yes-for-downloads --output-dir=dist_nuitka --macos-create-app-bundle 'src/MiniDexed Service Utility.py'
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            python -m nuitka --assume-yes-for-downloads --output-dir=dist_nuitka --onefile --windows-console-mode=attach --include-package=comtypes.client 'src/MiniDexed Service Utility.py' 
          else
             python -m nuitka --assume-yes-for-downloads --output-dir=dist_nuitka --onefile 'src/MiniDexed Service Utility.py'
          fi
          rm -rf dist_nuitka/*build
          rm -rf dist_nuitka/*dist # --standalone puts the executable in the dist folder

      env:
          PYTHONOPTIMIZE: 2
      shell: bash   

    - name: Upload Nuitka Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.build_type }}-${{ runner.arch }}
        path: |
          dist_nuitka/*
        retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Download Executable
      uses: actions/download-artifact@v4
      with:
        path: ./executables/
        # merge-multiple: true

    - name: Display structure of downloaded files
      run: ls -la executables/

    - name: Prepare release files
      run: |
        mkdir -p release
        # Debug: Show the actual structure
        find executables -type f -name "*MiniDexed*" -o -name "*.exe" -o -name "*.bin"
        
        # Rename and organize files for release
        find executables -name "*MiniDexed Service Utility.exe" -exec cp {} release/MiniDexed-Service-Utility-windows.exe \;
        find executables -name "*MiniDexed Service Utility.bin" -path "*linux-X64*" -exec cp {} release/MiniDexed-Service-Utility-linux \;
        find executables -name "*MiniDexed Service Utility.bin" -path "*linux-arm64*" -exec cp {} release/MiniDexed-Service-Utility-linux-arm64 \;
        find executables -name "*MiniDexed Service Utility" -path "*macos*" -exec cp {} release/MiniDexed-Service-Utility-macos \;
        find executables -name "*MiniDexed Service Utility.bin" -path "*alpine-musl-X64*" -exec cp {} release/MiniDexed-Service-Utility-linux-musl \;
        find executables -name "*MiniDexed Service Utility.bin" -path "*alpine-musl-arm64*" -exec cp {} release/MiniDexed-Service-Utility-linux-musl-arm64 \;
        
        # Make Linux/macOS binaries executable (only if they exist)
        find release -name "*linux*" -o -name "*macos*" | xargs -r chmod +x
        
        # List final release files
        ls -la release/ || echo "No files found in release directory"

    - name: Zip Artifacts
      run: |
        cd release
        for file in *; do
          if [ -f "$file" ]; then
            zip "$file.zip" "$file"
          fi
        done
        ls -lh *.zip

    - name: Upload binaries to release using uploadtool
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UPLOADTOOL_BODY: "Automated build from commit ${{ github.sha }}\\nBuilt on ${{ github.event.head_commit.timestamp }}\\nBranch: ${{ github.ref_name }}"
      run: |
        set -e
        cd release
        ls -lh *.zip # Show what we're about to upload
        wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh *.zip
