name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-10.15, windows-2016]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile src/main.py
      env:
        PYINSTALLER_STRIP: 1
        PYINSTALLER_UPX: 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-executable
        path: |
          dist/*.exe
          dist/*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Windows Executable
      uses: actions/download-artifact@v3
      with:
        name: windows-latest-executable
        path: ./executables/windows
    
    - name: Download macOS Executable
      uses: actions/download-artifact@v3
      with:
        name: macos-latest-executable
        path: ./executables/macos
    
    - name: Download Linux Executable
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-latest-executable
        path: ./executables/linux

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./executables/*
        token: ${{ secrets.GITHUB_TOKEN }}
